# Generated by Django 3.0.3 on 2020-08-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20200806_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_by',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
