# Generated by Django 3.0.3 on 2020-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20200826_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
