# Generated by Django 3.0.3 on 2020-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0021_auto_20200906_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileupload', models.FileField(upload_to='images')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
